Class {
	#name : #EbDictionaryParserExamples,
	#superclass : #EbDictionaryGrammarExamples,
	#category : #EberbanGt
}

{ #category : #accessing }
EbDictionaryParserExamples >> argument [
	<gtExample>
	^super argument
]

{ #category : #accessing }
EbDictionaryParserExamples >> lineBreaks [
	<gtExample>
	^super lineBreaks
]

{ #category : #accessing }
EbDictionaryParserExamples >> parserClass [
	^EbDictionaryParser
]

{ #category : #accessing }
EbDictionaryParserExamples >> sampleText [
	<gtExample>
	^ super sampleText
]
